---
- name: installing http
  hosts: all
  become: true
   
  tasks:
    - name: install httpd on redhat
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: install apacche2 on ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Ubuntu"
