---
- name: file module
  hosts: all
  become: true

  tasks:
  -  name: creating a file
     file:
       path: /tmp/newfile.txt
       state: touch
       owner: raheel
       group: raheel
       mode: u=rwx,g=rw,o=r

  - name: creating directoty
    file:
      path: /tmp/myfolder
      state: directory
