---
- name: install and start service
  hosts: all
  become: True

  tasks:
  - name: install nginx 
    yum:
      name: nginx
      state: present
  - name: starting the nginx service
    service:
      name: nginx
      state: started
      enabled: True


    


