---
- name: install and start service
  hosts: all
  become: True
  vars:
    - app: nginx


  tasks:
  - name: install nginx 
    yum:
      name: "{{ app }}"
      state: present
    tags: i-nginx

  - name: starting the nginx service
    service:
      name: "{{ app }}"
      state: started
      enabled: True
    tags: ss-nginx


    


